routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// FrontEndController

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/subscription', [FrontendController::class, 'subscription'])->name('subscription')->middleware('auth');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show')->middleware('verifyPreviewPost');
Route::get('/blogs/{post}/preview', [FrontendController::class, 'preview'])->name('blogs.preview')->middleware('verifyPreviewPost');
Route::get('/blogs/categories/{category}', [FrontendController::class, 'categories'])->name('blogs.categories');
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tags'])->name('blogs.tags');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

// Application Routes
Route::middleware(['auth'])->group(function() {

    Route::put('categories/approve/{category}', [CategoriesController::class, 'approve'])->name('categories.approve');
    Route::put('categories/disapprove/{category}', [CategoriesController::class, 'disApprove'])->name('categories.disapprove');
    Route::resource('categories', CategoriesController::class);
    
    Route::put('tags/approve/{tag}', [TagsController::class, 'approve'])->name('tags.approve');
    Route::put('tags/disapprove/{tag}', [TagsController::class, 'disApprove'])->name('tags.disapprove');
    Route::resource('tags', TagsController::class);
    
    Route::get('comments/', [CommentsController::class, 'index'])->name('comments.index');
    Route::post('comments/', [CommentsController::class, 'store'])->name('comments.store');
    Route::put('comments/approve/{comment}', [CommentsController::class, 'approve'])->name('comments.approve');
    Route::put('comments/disapprove/{comment}', [CommentsController::class, 'disApprove'])->name('comments.disapprove');

    Route::delete('posts/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/drafted', [PostsController::class, 'drafted'])->name('posts.drafted');
    Route::put('posts/publishDrafted/{post}', [PostsController::class, 'publishDrafted'])->name('posts.publishDrafted');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
    Route::put('posts/approve/{post}', [PostsController::class, 'approve'])->name('posts.approve');
    Route::put('posts/disapprove/{post}', [PostsController::class, 'disApprove'])->name('posts.disapprove');
    Route::resource('posts', PostsController::class);
    
    Route::delete('users/trash/{user}', [UsersController::class, 'trash'])->name('users.trash');
    Route::put('users/restore/{user}', [UsersController::class, 'restore'])->name('users.trashed');
    Route::get('users/trashed', [UsersController::class, 'trashed'])->name('users.trashed');
    Route::put('users/make-admin/{user}', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('users/revoke-admin/{user}', [UsersController::class, 'revokeAdmin'])->name('users.revoke-admin');
    Route::post('users/{user}/subscribe', [UsersController::class, 'subscribe'])->name('users.subscribe');
    Route::put('users/{user}/renew-subscription', [UsersController::class, 'renewSubscription'])->name('users.renewSubscription');
    Route::resource('users', UsersController::class);
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function posts()
    {
        return $this->belongsToMany(Post::class)->withTimestamps();
    }

    public function scopeApproved($query) {
        return $query->where('approved_at', '!=', null);
    }

    public function isApproved(): bool {
        return isset($this->approved_at);
    }

    public function isPending(): bool {
        return !(isset($this->approved_at) xor isset($this->disapproved_at));
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTagRequest;
use App\Http\Requests\UpdateTagRequest;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('admin')->only('edit', 'update', 'destroy', 'approve', 'disApprove');
    }

    public function index()
    {
        $tags = Tag::paginate(5);
        return view('tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        Tag::create([
            'name' => $request->name
        ]);
        session()->flash('success', 'Tag created successfully!');
        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.edit', ['tag' => $tag]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->update([
            'name'=> $request->name,
            'approver_id' => null,
            'approved_at' => null,
            'disapprover_id' => null,
            'disapproved_at' => null
        ]);
        session()->flash('success', 'Tag Updated Successfully!');
        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        if($tag->posts->count() > 0) {
            session()->flash('error', 'This Tag cannot be deleted!');
            return redirect(route('tags.index'));
        }
        $tag->delete();
        session()->flash('success', 'Tag Deleted Successfully!');
        return redirect(route('tags.index'));
    }

    public function approve(Tag $tag) {
        $tag->update([
            'approver_id' => auth()->id(),
            'approved_at' => now(),
            'disapprover_id' => null,
            'disapproved_at' => null
        ]);
        session()->flash('success', 'Tag Approved Successfully');
        return redirect(route('tags.index'));
    }

    public function disApprove(Tag $tag) {
        if($tag->posts->count() > 0) {
            session()->flash('error', 'This Tag cannot be disapproved!');
            return redirect(route('tags.index'));
        }
        $tag->update([
            'disapprover_id' => auth()->id(),
            'disapproved_at' => now(),
            'approver_id' => null,
            'approved_at' => null
        ]);
        session()->flash('success', 'Tag Disapproved Successfully');
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.admin-panel.app')

@section('title', 'WayToBlog')

@section('content')

    <div class="card">
        <div class="card-header h2">Add a Tag</div>
        <div class="card-body">
            <form action="{{ route('tags.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name" class="@error('name') text-danger @enderror" >Name</label>
                    <input  type="text"
                            class="form-control @error('name') is-invalid @enderror"
                            id="name"
                            name="name"
                            value="{{ old('name') }}"
                            placeholder="Enter Tag Name">
                    @error('name')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-success float-right px-4">Add</button>
            </form>
        </div>
    </div>

@endsection

resources/views/tags/edit.blade.php
@extends('layouts.admin-panel.app')

@section('title', 'WayToBlog')

@section('content')

    <div class="card">
        <div class="card-header h2">Edit a Tag</div>
        <div class="card-body">
            <form action="{{ route('tags.update', $tag->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name" class="@error('name') text-danger @enderror" >Name</label>
                    <input  type="text"
                            class="form-control @error('name') is-invalid @enderror"
                            id="name"
                            name="name"
                            value="{{ old('name', $tag->name) }}"
                            placeholder="Enter tag Name">
                    @error('name')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-primary float-right px-4">Edit</button>
            </form>
        </div>
    </div>

@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin-panel.app')

@section('title', 'WayToBlog')

@section('content')

    <div class="d-flex justify-content-end align-items-center mb-3">
        <a href="{{ route('tags.create') }}" class="btn bg-red-500 text-gray-50 border-red-500 hover:bg-white hover:text-red-500 d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
            </svg>
             Add a Tag</a>
    </div>
    @if(!$tags->isEmpty())
        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col">Tag</th>
                <th scope="col">Posts</th>
                <th scope="col">Status</th>
                @if(auth()->user()->isAdmin())
                    <th scope="col">Actions</th>
                @endif
                </tr>
            </thead>
            <tbody>
                @foreach ($tags as $tag)
                <tr>
                    <th scope="row">{{ $tag->name }}</th>
                    <th scope="row">{{ $tag->posts->count() }}</td>
                    <th scope="row">
                        @if($tag->isPending())
                    <div class="text-sm text-yellow-500 inline-flex align-middle">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                        </svg>
                        Approval pending
                    </div>
                @elseif($tag->isApproved())
                    <div class="text-sm text-success inline-flex"><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>Approved</div>
                @else
                    <div class="text-sm text-danger inline-flex">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>Disapproved</div>
                @endif    
                    </td>
                    @if(auth()->user()->isAdmin())
                        <td class="flex">
                            @if (auth()->user()->isAdmin() && (!$tag->isApproved()))
                                <form action="{{ route('tags.approve', $tag->id) }}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <button type="submit" class="btn btn-outline-success flex mr-3">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                        Approve
                                    </button>
                                </form>
                            @elseif (auth()->user()->isAdmin() && $tag->isApproved())
                                <form action="{{ route('tags.disapprove', $tag->id) }}" method="post">    
                                    @csrf
                                    @method('PUT')
                                    <button type="submit" class="btn btn-outline-danger flex mr-3">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                        Disapprove
                                    </button>
                                </form>
                            @endif
                            <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-outline-primary mr-3">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                </svg>
                            </a>
                            <a href="#deleteModal" class="btn btn-outline-danger" onclick="displayModal({{ $tag->id }})" data-toggle="modal">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.4" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                </svg>
                            </a>
                        </td>
                    @endif
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div class="mt-5">
        {{ $tags->links('vendor.pagination.bootstrap-4') }}
    </div>
    @else
        <div class="text-2xl">There are no tags here.</div>
    @endif

	<!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you want to delete this tag?</p>
            </div>
            <div class="modal-footer">
                <form action="" method="POST" id="deleteTagForm">
                    @csrf
                    @method('DELETE')
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn bg-red-500 text-gray-50 border-red-500 hover:bg-white hover:text-red-500" value="Delete tag">
                </form>
            </div>
            </div>
        </div>
    </div>

@endsection

@section('page-level-script')
    <script>
        function displayModal(tagId) {
            var url = '/tags/' + tagId;
            $('#deleteTagForm').attr('action', url);
        }
    </script>
@endsection