routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// FrontEndController

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/subscription', [FrontendController::class, 'subscription'])->name('subscription')->middleware('auth');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show')->middleware('verifyPreviewPost');
Route::get('/blogs/{post}/preview', [FrontendController::class, 'preview'])->name('blogs.preview')->middleware('verifyPreviewPost');
Route::get('/blogs/categories/{category}', [FrontendController::class, 'categories'])->name('blogs.categories');
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tags'])->name('blogs.tags');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

// Application Routes
Route::middleware(['auth'])->group(function() {

    Route::put('categories/approve/{category}', [CategoriesController::class, 'approve'])->name('categories.approve');
    Route::put('categories/disapprove/{category}', [CategoriesController::class, 'disApprove'])->name('categories.disapprove');
    Route::resource('categories', CategoriesController::class);
    
    Route::put('tags/approve/{tag}', [TagsController::class, 'approve'])->name('tags.approve');
    Route::put('tags/disapprove/{tag}', [TagsController::class, 'disApprove'])->name('tags.disapprove');
    Route::resource('tags', TagsController::class);
    
    Route::get('comments/', [CommentsController::class, 'index'])->name('comments.index');
    Route::post('comments/', [CommentsController::class, 'store'])->name('comments.store');
    Route::put('comments/approve/{comment}', [CommentsController::class, 'approve'])->name('comments.approve');
    Route::put('comments/disapprove/{comment}', [CommentsController::class, 'disApprove'])->name('comments.disapprove');

    Route::delete('posts/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/drafted', [PostsController::class, 'drafted'])->name('posts.drafted');
    Route::put('posts/publishDrafted/{post}', [PostsController::class, 'publishDrafted'])->name('posts.publishDrafted');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
    Route::put('posts/approve/{post}', [PostsController::class, 'approve'])->name('posts.approve');
    Route::put('posts/disapprove/{post}', [PostsController::class, 'disApprove'])->name('posts.disapprove');
    Route::resource('posts', PostsController::class);
    
    Route::delete('users/trash/{user}', [UsersController::class, 'trash'])->name('users.trash');
    Route::put('users/restore/{user}', [UsersController::class, 'restore'])->name('users.trashed');
    Route::get('users/trashed', [UsersController::class, 'trashed'])->name('users.trashed');
    Route::put('users/make-admin/{user}', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('users/revoke-admin/{user}', [UsersController::class, 'revokeAdmin'])->name('users.revoke-admin');
    Route::post('users/{user}/subscribe', [UsersController::class, 'subscribe'])->name('users.subscribe');
    Route::put('users/{user}/renew-subscription', [UsersController::class, 'renewSubscription'])->name('users.renewSubscription');
    Route::resource('users', UsersController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Thomaswelton\LaravelGravatar\Facades\Gravatar;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    const MEMBER_APPROVER = 1;
    const ADMIN = 'admin';
    const AUTHOR = 'author';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function subscription()
    {
        return $this->hasOne(Subscription::class);
    }

    public function isMember(): bool
    {
        return $this->subscription && now()->lessThan($this->subscription->ends_at);
    }

    public function wasMember(): bool
    {
        return $this->subscription && now()->greaterThanOrEqualTo($this->subscription->ends_at);
    }
    
    public function isAdmin(): bool
    {
        return $this->role === self::ADMIN;
    }

    function getGravatarImageAttribute() {
	    return Gravatar::src($this->email, 80);
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\DeleteUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth','admin'])->except('edit', 'update', 'trash', 'subscribe', 'renewSubscription');
        $this->middleware(['validateUser'])->only('edit', 'update', 'trash', 'subscribe', 'renewSubscription');
    }

    public function index(){
        $users = User::paginate(10);
        return view('users.index',compact(['users']));
    }

    public function makeAdmin(User $user){
        $user->update(['role' => User::ADMIN]);
        session()->flash('success', $user->name . ' has been assigned admin role!');
        return redirect(route('users.index'));
    }

    public function revokeAdmin(User $user){
        $user->update(['role' => User::AUTHOR]);
        session()->flash('success', $user->name . ' has been revoked admin role!');
        return redirect(route('users.index'));
    }

    public function create()
    {
        return view('users.create');
    }

    
    public function store(CreateUserRequest $request)
    {
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password)
        ]);
        session()->flash('success', 'User Created Successfully!');
        return redirect(route('users.index'));
    }

    public function edit(User $user)
    {
        return view('users.edit', compact(['user']));
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        if($request->password != '') {
            $password = Hash::make($request->password);
        } else {
            $password = $user->password;
        }
        $user->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $password
        ]);
        session()->flash('success', 'User Updated Successfully!');
        return redirect(route('users.index'));
    }

    public function destroy($id)
    {
        $user = User::onlyTrashed()->findOrFail($id);
        $user->forceDelete();
        session()->flash('success', 'User Deleted successfully!');
        return redirect(route('users.trashed'));
    }
    
    public function trash(DeleteUserRequest $request, User $user)
    {
        $user->delete();
        return redirect(route('home'));
    }

    public function trashed()
    {
        $users = User::onlyTrashed()->paginate(10);
        return view('users.trashed', compact(['users']));
    }

    public function restore($id)
    {
        $trashedUser = User::onlyTrashed()->findOrFail($id);
        $trashedUser->restore();
        session()->flash('success', 'User Restored Successfully!');
        return redirect(route('users.index'));
    }

    public function subscribe(User $user)
    {
        $user->subscription()->create([
            'started_at' => now(),
            'ends_at' => now()->addDays(1)
        ]);
        return redirect(route('subscription'));
    }

    public function renewSubscription(User $user)
    {
        $user->subscription->update([
            'started_at' => now(),
            'ends_at' => now()->addDays(1)
        ]);
        return redirect(route('subscription'));
    }

}

resources/views/users/create.blade.php
@extends('layouts.admin-panel.app')

@section('title', 'WayToBlog')

@section('content')

    <div class="card">
        <div class="card-header h2">Add User</div>
        <div class="card-body">
            <form action="{{ route('users.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name" class="@error('name') text-danger @enderror" >Name</label>
                    <input  type="text"
                            class="form-control @error('name') is-invalid @enderror"
                            id="name"
                            name="name"
                            value="{{ old('name') }}"
                            placeholder="Enter Name">
                    @error('name')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="email" class="@error('email') text-danger @enderror" >Email</label>
                    <input  type="text"
                            class="form-control @error('email') is-invalid @enderror"
                            id="email"
                            name="email"
                            value="{{ old('email') }}"
                            placeholder="Enter email">
                    @error('email')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password" class="@error('password') text-danger @enderror" >Password</label>
                    <input  type="password"
                            class="form-control @error('password') is-invalid @enderror"
                            id="password"
                            name="password"
                            value="{{ old('password') }}"
                            placeholder="Enter password">
                    @error('password')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-success float-right px-4">Add</button>
            </form>
        </div>
    </div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.admin-panel.app')

@section('title', 'WayToBlog')

@section('content')

    <div class="card">
        <div class="card-header h2">Edit Profile</div>
        <div class="card-body">
            <form action="{{ route('users.update', $user->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name" class="@error('name') text-danger @enderror" >Name</label>
                    <input  type="text"
                            class="form-control @error('name') is-invalid @enderror"
                            id="name"
                            name="name"
                            value="{{ old('name', $user->name) }}"
                            placeholder="Enter Name">
                    @error('name')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="email" class="@error('email') text-danger @enderror" >Email</label>
                    <input  type="text"
                            class="form-control @error('email') is-invalid @enderror"
                            id="email"
                            name="email"
                            value="{{ old('email', $user->email) }}"
                            placeholder="Enter email">
                    @error('email')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password" class="@error('password') text-danger @enderror" >Password</label>
                    <input  type="password"
                            class="form-control is-valid @error('password') is-invalid @enderror"
                            id="password"
                            name="password"
                            value="{{ old('password') }}"
                            placeholder="Enter password">
                    @error('password')
                        <small class="form-text text-danger password-error">{{ $message }}</small>
                    @enderror
                        <small class="form-text text-success password-text">Leave the field empty if you do not wish to change password!</small>
                </div>
                <button type="submit" class="btn btn-outline-success float-right px-4">Update Changes!</button>
            </form>
        </div>
    </div>

@endsection

@section('page-level-scripts')
    <script>
        
        if($('.password-error').length > 0) {
            $('.password-text').css('display', 'none');
        }
    </script>    
@endsection

resources/views/users/index.blade.php
@extends('layouts.admin-panel.app')

@section('title', 'WayToBlog | Users')

@section('content')
    <div class="d-flex justify-content-end align-items-center mb-3">
        <a href="{{ route('users.create') }}" class="btn bg-red-500 text-gray-50 border-red-500 hover:bg-white hover:text-red-500 d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
            </svg>
            Add User</a>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
            <th scope="col">Image</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col" class="text-center">Posts</th>
            <th scope="col" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td><img src="{{asset("$user->gravatar_image")}}" class="rounded-circle"></td>
                    <td style="line-height: 80px;">
                        {{ $user->name }}
                    </td>
                    <td style="line-height: 80px;">{{ $user->email }}</td>
                    <td class="text-center" style="line-height: 80px;">{{ $user->posts->count() }}</td>
                    <td class="text-center" style="line-height: 80px;">
                        @if(Auth::user()->id == $user->id)
                            <a href="{{ route('users.edit', $user->id) }}" class="btn text-red-500 border-red-500 hover:bg-red-500 hover:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                </svg>
                            </a>
                        @endif
                        @if(!$user->isAdmin())
                            <form action="{{route('users.make-admin', $user->id)}}" method="POST">
                                @csrf
                                @method('PUT')
                                <button type="submit" class="btn btn-outline-success">Make Admin</button>
                            </form>
                        @elseif(Auth::user()->id != $user->id)
                            <form action="{{route('users.revoke-admin', $user->id)}}" method="POST">
                                @csrf
                                @method('PUT')
                                <button type="submit" class="btn btn-outline-danger">Revoke Admin</button>
                            </form>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="mt-5">
        {{$users->links('vendor.pagination.bootstrap-4')}}
    </div>
@endsection

resources/views/users/trashed.blade.php
@extends('layouts.admin-panel.app')

@section('title', 'WayToBlog')

@section('content')

    @if(!$users->isEmpty())
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Image</th>	
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Posts</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                <tr style="height: 80px;">
                    <th scope="row">
                        <img src="{{ asset($user->gravatar_image) }}" class="rounded-circle">
                    </td>
                    <th scope="row" style="line-height: 80px;">{{ $user->name }}</td>
                    <th scope="row" style="line-height: 80px;">{{ $user->email }}</td>
                    <th scope="row" style="line-height: 80px;">{{ $user->posts->count() }}</td>
                    <td style="line-height: 80px;">
                            <a href="#restoreModal" type="submit" class="btn btn-outline-primary d-inline-block mr-2" onclick="displayRestoreModal({{ $user->id }})" data-toggle="modal">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2 d-inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16 15v-1a4 4 0 00-4-4H8m0 0l3 3m-3-3l3-3m9 14V5a2 2 0 00-2-2H6a2 2 0 00-2 2v16l4-2 4 2 4-2 4 2z" />
                                </svg>
                                Restore
                            </a>
                            <a href="#deleteModal" class="btn btn-outline-danger ml-2" onclick="displayModal({{ $user->id }})" data-toggle="modal">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                </svg>
                            </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="mt-5">
            {{ $users->links('vendor.pagination.bootstrap-4') }}
        </div>
    @else
        <div class="text-2xl">There are no users here.</div>
    @endif
    

    <!-- Restore MODAL -->
    <div class="modal fade" id="restoreModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Restore</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you want to restore this user?</p>
            </div>
            <div class="modal-footer">
                <form action="" method="POST" id="restoreuserForm">
                    @csrf
                    @method('PUT')
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn bg-red-500 text-gray-50 border-red-500 hover:bg-white hover:text-red-500">Restore</button>
                </form>
            </div>
            </div>
        </div>
    </div>

    <!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>This user will be deleted permanantly. Do you want to proceed?</p>
            </div>
            <div class="modal-footer">
                <form action="" method="POST" id="deleteuserForm">
                    @csrf
                    @method('DELETE')
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-outline-danger" value="Delete">
                </form>
            </div>
            </div>
        </div>
    </div>

@endsection

@section('page-level-scripts')
    <script>
        function displayModal(userId) {
            var url = '/users/' + userId;
            $('#deleteuserForm').attr('action', url);
        }
        function displayRestoreModal(userId) {
            var url = '/users/restore/' + userId;
            $('#restoreuserForm').attr('action', url);
        }
    </script>
@endsection