routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// FrontEndController

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/subscription', [FrontendController::class, 'subscription'])->name('subscription')->middleware('auth');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show')->middleware('verifyPreviewPost');
Route::get('/blogs/{post}/preview', [FrontendController::class, 'preview'])->name('blogs.preview')->middleware('verifyPreviewPost');
Route::get('/blogs/categories/{category}', [FrontendController::class, 'categories'])->name('blogs.categories');
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tags'])->name('blogs.tags');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

// Application Routes
Route::middleware(['auth'])->group(function() {

    Route::put('categories/approve/{category}', [CategoriesController::class, 'approve'])->name('categories.approve');
    Route::put('categories/disapprove/{category}', [CategoriesController::class, 'disApprove'])->name('categories.disapprove');
    Route::resource('categories', CategoriesController::class);
    
    Route::put('tags/approve/{tag}', [TagsController::class, 'approve'])->name('tags.approve');
    Route::put('tags/disapprove/{tag}', [TagsController::class, 'disApprove'])->name('tags.disapprove');
    Route::resource('tags', TagsController::class);
    
    Route::get('comments/', [CommentsController::class, 'index'])->name('comments.index');
    Route::post('comments/', [CommentsController::class, 'store'])->name('comments.store');
    Route::put('comments/approve/{comment}', [CommentsController::class, 'approve'])->name('comments.approve');
    Route::put('comments/disapprove/{comment}', [CommentsController::class, 'disApprove'])->name('comments.disapprove');

    Route::delete('posts/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/drafted', [PostsController::class, 'drafted'])->name('posts.drafted');
    Route::put('posts/publishDrafted/{post}', [PostsController::class, 'publishDrafted'])->name('posts.publishDrafted');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
    Route::put('posts/approve/{post}', [PostsController::class, 'approve'])->name('posts.approve');
    Route::put('posts/disapprove/{post}', [PostsController::class, 'disApprove'])->name('posts.disapprove');
    Route::resource('posts', PostsController::class);
    
    Route::delete('users/trash/{user}', [UsersController::class, 'trash'])->name('users.trash');
    Route::put('users/restore/{user}', [UsersController::class, 'restore'])->name('users.trashed');
    Route::get('users/trashed', [UsersController::class, 'trashed'])->name('users.trashed');
    Route::put('users/make-admin/{user}', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('users/revoke-admin/{user}', [UsersController::class, 'revokeAdmin'])->name('users.revoke-admin');
    Route::post('users/{user}/subscribe', [UsersController::class, 'subscribe'])->name('users.subscribe');
    Route::put('users/{user}/renew-subscription', [UsersController::class, 'renewSubscription'])->name('users.renewSubscription');
    Route::resource('users', UsersController::class);
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $guarded = ['id'];
    protected $dates = ['published_at', 'approved_at', 'disapproved_at'];

    // Accessor
    public function getImagePathAttribute()
    {
        return 'storage/'.$this->image;
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function comments()
    {
        return $this->hasMany(Comment::class)->commented()->approved();
    }

    public function hasTag(int $tag_id): bool
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function isApproved(): bool {
        return isset($this->approved_at);
    }

    public function isPending(): bool {
        return !(isset($this->approved_at) xor isset($this->disapproved_at));
    }

    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    // Accessors
    public function getApproverAttribute() {
        return User::findOrFail($this->approver_id);
    }

    public function getDisapproverCommentAttribute() {
        // return $this->disapprover_comment;
        return $this->attributes['disapprover_comment'];
    }

    // Query Scopes

    public function scopePublishedAndScheduled($query)
    {
        return $query->where('published_at', '!=', null);
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now());
    }

    public function scopeDrafted($query)
    {
        return $query->where('published_at', null);
    }

    public function scopeSearch($query)
    {
        $search = request('search');
        if($search) {
            return $query->where('title', 'LIKE', "%$search%")
                    ->orWhere('excerpt', 'LIKE', "%$search%");
        }
        return $query;
    }

    public function scopeApproved($query) {
        return $query->where('approved_at', '!=', null);
    }

    public function scopeUserPosts($query) {
        $query->where('user_id', auth()->id());
    }

}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DisapprovePostRequest;
use App\Http\Requests\posts\CreatePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Http\JsonResponse;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware(['auth', 'admin'])->only('approve', 'disApprove');
        $this->middleware(['verifyCategoriesCount'])->only('create', 'store');
        $this->middleware(['verifyTagsCount'])->only('create', 'store');
        $this->middleware(['validateAuthor'])->only('edit', 'update', 'trash', 'restore');
    }

    public function index()
    {
        if(auth()->user()->isAdmin()) {
            $posts = Post::publishedAndScheduled()->paginate(3);
        }else {
            $posts = Post::userPosts()->publishedAndScheduled()->paginate(3);
        }
        return view('posts.index', compact(['posts']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::approved()->get();
        $tags = Tag::approved()->get();
        return view('posts.create', compact(['categories', 'tags']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $isMember = auth()->user()->isMember();
        $data = $request->only(['title', 'excerpt', 'content', 'category_id', 'tags[]']);
        if(isset($request->submit)) {
            $data['published_at'] = now();
            if($isMember) {
                if($request->publish == 'future') {
                    $data['published_at'] = $request->published_at;
                }
                $data['approver_id'] = User::MEMBER_APPROVER;
                $data['approved_at'] = $request->published_at;
            } else {
                $data['approver_id'] = null;
                $data['approved_at'] = null;
            }
        } else {
            $data['published_at'] = null;
        }
        $data['user_id'] = auth()->id();
        $image = $request->file('image')->store('images/posts');
        $data['image'] = $image;
        $post = Post::create($data);
        $post->tags()->attach($request->tags);
        $isMember? session()->flash('success', 'Your Blog is live!') : session()->flash('success', 'Your Blog is uploaded and will be published shortly!');
        if(isset($request->submit)) {
            return redirect(route('posts.index'));
        } else {
            return redirect(route('posts.drafted'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::approved()->get();
        $tags = Tag::approved()->get();
        return view('posts.edit', compact(['post', 'categories', 'tags']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $isMember = auth()->user()->isMember();
        $data = $request->only(['title', 'excerpt', 'content', 'category_id']);
        if(isset($request->submit)) {
            $data['published_at'] = now();
            if($isMember) {
                if($request->publish == 'future') {
                    $data['published_at'] = $request->published_at;
                }
                /**
                 * If the disapproved_at is set, it means that a (pro member)author's post is disapproved, then even though the author is a member, we don't wanna give auto-member-approval on this post. hence, the below code;
                 */
                if(!isset($post->disapproved_at)) {
                    $data['approver_id'] = User::MEMBER_APPROVER;
                    $data['approved_at'] = $request->published_at;
                } else {
                    $data['approver_id'] = null;
                    $data['approved_at'] = null;
                    session()->flash('success', 'Your post is updated but needs approval as it had been disapproved before!');
                }
            } else { // If it is not member, the author will need approval from an admin to get the post li
                $data['approver_id'] = null;
                $data['approved_at'] = null;
            }
        } else {
            $data['published_at'] = null;
            session()->flash('success', 'Your post is marked as draft!');
        }
        if($request->hasFile('image')) {
            $image = $request->image->store('images/posts');
            $data['image'] = $image;
            $post->deleteImage();
        }

        $data['user_id'] = auth()->id();
        $data['disapprover_id'] = null;
        $data['disapproved_at'] = null;
        $data['disapprover_comment'] = null;
        $post->update($data);

        $post->tags()->sync($request->tags);

        if(!session()->exists('success')) {
            $isMember? session()->flash('success', 'Your Blog is published!') : session()->flash('success', 'Your Blog is updated and will be published shortly!');
        }

        if(isset($request->submit)) {
            return redirect(route('posts.index'));
        } else {
            return redirect(route('posts.drafted'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->deleteImage();
        $post->forceDelete();
        session()->flash('success', 'Post Deleted successfully!');
        return redirect(route('posts.trashed'));
    }

    public function trashed()
    {
        if(auth()->user()->isAdmin()) {
            $trashed = Post::onlyTrashed()->paginate(10);
        } else {
        $trashed = Post::userPosts()->onlyTrashed()->paginate(10);
        }
        return view('posts.trashed', ['posts' => $trashed]);
    }

    public function drafted()
    {
        $drafted = Post::userPosts()->drafted()->paginate(5);
        return view('posts.drafted', ['posts' => $drafted]);
    }

    public function publishDrafted(Post $post)
    {
        $data['published_at'] = now();
        if(auth()->user()->isMember()) {
            $data['approved_at'] = now();
            $data['approver_id'] = User::MEMBER_APPROVER;
        }

        $post->update($data);
        session()->flash('success', 'Post Published Successfully!');
        return redirect(route('posts.index'));
    }

    public function trash(Post $post)
    {
        $post->update([
            'disapprover_id' => null,
            'disapproved_at' => null,
            'approver_id' => null,
            'approved_at' => null,
            'disapprover_comment' => null
        ]);
        $post->delete();
        session()->flash('success', 'Post Trashed successfully!');
        return redirect(route('posts.trashed'));
    }

    public function restore($id)
    {
        $trashedPost = Post::onlyTrashed()->findOrFail($id);
        $trashedPost->restore();
        session()->flash('success', 'Post Restored Successfully!');
        return redirect(route('posts.index'));
    }

    public function approve(Post $post) {
        $post->update([
            'approver_id' => auth()->id(),
            'approved_at' => now(),
            'disapprover_id' => null,
            'disapproved_at' => null,
            'disapprover_comment' => null,
        ]);
        session()->flash('success', 'Post Approved Successfully');
        return redirect(route('posts.index'));
    }

    public function disApprove(DisapprovePostRequest $request, Post $post) {
        $post->update([
            'disapprover_id' => auth()->id(),
            'disapproved_at' => now(),
            'disapprover_comment' => $request->comment,
            'approver_id' => null,
            'approved_at' => null
        ]);
        session()->flash('success', 'Post Disapproved Successfully');
        return redirect(route('posts.index'));
    }

    public function getPostsJson(): JsonResponse
    {
        /**
         * Data to be returned: -
                title
                date
                authorName
                rating
                views
                description
         */

        /*
        return Post::with('author')->get()->map->only(['id', 'author', 'title', 'published_at', 'excerpt'])->map(function ($post) {
            $post['author'] = [
                "name" => $post['author']->name,
                "avatar" => $post['author']->gravatar_image
            ];
            $post['date'] = $post['published_at']->diffForHumans();
            $post['image'] = asset('storage/images/posts/1.jpg');
            $post['description'] = $post['excerpt'];
            $post['views'] = 120;
            $post['rating'] = 5.0;
        })->toJson();
        */

        $posts = Post::with('author')->publishedAndScheduled()->approved()->get();
        $blogData = [
            'data' => [],
        ];
        foreach($posts as $post) {
            $temp['id'] = $post->id;
            $temp['author'] = [
                "name" => $post->author->name,

resources/views/posts/index.blade.php
@extends('layouts.admin-panel.app')

@section('title', 'WayToBlog')

@section('errors')
    @error('comment')
        {{ session()->flash('error', $errors->first('comment')) }}
    @enderror
@endsection

@section('content')

    <div class="d-flex justify-content-end align-items-center mb-3">
        <a href="{{ route('posts.create') }}" class="btn bg-red-500 text-gray-50 border-red-500 hover:bg-white hover:text-red-500 d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
            </svg>
            Add Post
        </a>
    </div>
    @if(!$posts->isEmpty())
        @foreach ($posts as $post)
            <div class="row g-0 border rounded relative overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                @if($post->isPending())
                    <div class="badge ml-2 self-center md:absolute md:top-0 md:right-0 m-4 px-2 py-2 rounded-full text-sm text-yellow-800 bg-yellow-500 font-medium flex leading-relaxed px-3">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                        </svg>
                        Approval pending
                    </div>
                @elseif($post->isApproved())
                    <div class="btn ml-2 self-center md:absolute md:top-0 md:right-0 m-4 px-2 py-2 rounded-full text-sm text-green-100 btn-success font-medium flex leading-relaxed px-3" @if($post->approver->id != 1) data-toggle="popover" data-placement="bottom" data-content="By {{ $post->approver->name }}" @endif><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        @if($post->approver->id === 1)
                        Member approved
                        @else
                        Approved
                        @endif
                    </div>
                @else
                    <button onclick="displayCommentModal('{{ $post->disapprover_comment }}')" data-toggle="modal" data-target="#commentModal" class="btn ml-2 self-center md:absolute md:top-0 md:right-0 m-4 px-2 py-2 rounded-full text-sm text-white btn-danger font-medium flex leading-relaxed px-3">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>Disapproved!
                    </button>
                @endif
                <div class="col-auto sm:w-px md:w-5/12 flex justify-center mx-auto align-center">
                    <img src="{{ asset($post->image_path) }}" class="rounded-xl object-fill img-fluid align-self-center sm:w-px md:w-full justify-self-center" width="382px">
                </div>
                <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">
                    <a class="text-red-500 hover:text-red-600" href="{{route('blogs.categories', $post->category->id)}}">{{ $post->category->name }}</a>
                </strong>

                <h3 class="mb-1 h4 md:w-3/5">{{ $post->title }}</h3>
                <div class="text-muted"><span class="text-gray-700">{{ $post->published_at > now()? 'Scheduled '.$post->published_at->format('jS F \\a\\t h:i') : 'Posted '.$post->published_at->diffForHumans() }}</span> &ndash; {{ 'By '.$post->author->name }}</div>
                <p class="card-text text-muted mt-2">{{ Str::limit($post->excerpt, (Str::length($post->excerpt)/2), '...') }}</p>
                <p class="card-text mb-3 text-gray-700">{{ strip_tags(Str::limit($post->content, (Str::length($post->content)/5), '...')) }}</p>
                <div class="d-flex flex-wrap  mt-2">
                @if (auth()->user()->isAdmin() && (!$post->isApproved()))
                    <form action="{{ route('posts.approve', $post->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <button type="submit" class="btn btn-outline-success flex mr-3">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            Approve
                        </button>
                    </form>
                @elseif (auth()->user()->isAdmin() && $post->isApproved())
                    <a href="#disapproveModal" class="btn btn-outline-danger flex mr-3" data-toggle="modal" onclick="displayDisapproveModal({{ $post->id }})">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        Disapprove
                    </a>
                @endif

                <a href="{{ route('blogs.preview', $post->id) }}" class="btn btn-outline-primary d-inline-block mr-3">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                </a>
                
                @if($post->user_id == auth()->id())
                    <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-outline-primary d-inline-block mr-3">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                        </svg>
                    </a>
                    <a href="#deleteModal" class="btn btn-outline-danger" onclick="displayDeleteModal({{ $post->id }})" data-toggle="modal">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                    </a>
                @endif
                </div>
                </div>
            </div>
        @endforeach
    @else
        <div class="text-2xl">There are no posts here.</div>
    @endif
    <div class="mt-5">
        {{ $posts->links('vendor.pagination.bootstrap-4') }}
    </div>

    <!-- Comment Modal -->
    <div class="modal fade" id="commentModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header text-danger">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </span>
                <h5 class="modal-title ml-2">Disapproved</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="mb-2 comment-text"></p>
            </div>
            </div>
            </div>
        </div>
    </div>

    <!-- Disapprove Modal -->
    <div class="modal fade" id="disapproveModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header text-danger">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </span>
                <h5 class="modal-title ml-2">Disapprove</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="mb-2">Why are you disapproving this post?</p>
                <form action="" method="post" id="disapproveForm">
                <textarea
                    type="text"
                    name="comment"
                    class="form-control"
                    placeholder="Leave a comment."
                ></textarea>
            </div>
            <div class="modal-footer">
                    @csrf
                    @method('PUT')
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-outline-danger" value="Disapprove">
                </form>
            </div>
            </div>
        </div>
    </div>

    <!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you wish to delete this post?</p>
            </div>
            <div class="modal-footer">
                <form action="" method="POST" id="deletepostForm">
                    @csrf
                    @method('DELETE')
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-outline-danger" value="Move to bin">
                </form>
            </div>
            </div>
        </div>
    </div>

@endsection

@section('page-level-scripts')
    <script>
        $(function () {
          $('[data-toggle="popover"]').popover()
        });
        function displayCommentModal(comment) {
            $('.comment-text').html(comment);
        };
        function displayDeleteModal(postId) {
            var url = '/posts/trash/' + postId;
            $('#deletepostForm').attr('action', url);
        };
        function displayDisapproveModal(postId) {
            var url = '/posts/disapprove/' + postId;
            $('#disapproveForm').attr('action', url);
        };
    </script>
@endsection